// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nuhyjfggcoueebijauvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51aHlqZmdnY291ZWViaWphdXZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxODA2MzEsImV4cCI6MjA3MTc1NjYzMX0.ev6p0EsYb75u9DO-h1AozZm2BR9XzQPzfeHEDBdcKzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});